export const INITIAL_SERVICES = [
  {
    id: "srv-1",
    name: "PRECISION CUT & ARCHITECTURE",
    slug: "precision-cut",
    category: "CUT",
    description: "Architectural Japanese scissors technique tailored to your natural bone structure, growth vectors, and movement.",
    price: 4500,
    duration: 60,
    imageUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 1,
    featured: true,
  },
  {
    id: "srv-2",
    name: "SIGNATURE BESPOKE STYLING",
    slug: "signature-style",
    category: "STYLING",
    description: "Effortless, tactile texture shaping with thermal protection and organic botanical finishing elixirs.",
    price: 3800,
    duration: 45,
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 2,
    featured: true,
  },
  {
    id: "srv-3",
    name: "HAUTE COUTURE COLOUR",
    slug: "couture-colour",
    category: "COLOUR",
    description: "Dimensional tonal mapping, root blending, and ammonia-free gloss formulation for sublime luminosity.",
    price: 8500,
    duration: 120,
    imageUrl: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 3,
    featured: true,
  },
  {
    id: "srv-4",
    name: "FRENCH BALAYAGE MELT",
    slug: "french-balayage",
    category: "BALAYAGE",
    description: "Freehand hand-painted gradient ribbons designed for seamless regrowth and soft daylight dimension.",
    price: 12000,
    duration: 180,
    imageUrl: "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 4,
    featured: true,
  },
  {
    id: "srv-5",
    name: "CELLULAR KERATIN & SCALP ELIXIR",
    slug: "cellular-treatment",
    category: "TREATMENT",
    description: "Micro-peptide reconstruction mask, botanical steam infusion, and deep lymphatic scalp rejuvenation.",
    price: 6500,
    duration: 75,
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 5,
    featured: true,
  },
  {
    id: "srv-6",
    name: "SCULPTED EDITORIAL BLOW DRY",
    slug: "editorial-blowdry",
    category: "STYLING",
    description: "Volumetric brushwork and cold-blast setting creating airy bounce, fluid sway, and high-gloss finish.",
    price: 3200,
    duration: 45,
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 6,
    featured: false,
  },
  {
    id: "srv-7",
    name: "MASCULINE GROOMING & TEXTURE",
    slug: "masculine-grooming",
    category: "GROOMING",
    description: "Tailored scissor-over-comb silhouette, hot towel conditioning, neck taper, and matte clay finish.",
    price: 3500,
    duration: 50,
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=80",
    active: true,
    order: 7,
    featured: false,
  },
];

export const INITIAL_STAFF = [
  {
    id: "stf-1",
    name: "AARAV SHAH",
    slug: "aarav-shah",
    role: "CREATIVE DIRECTOR & FOUNDER",
    bio: "Formally trained in London and Milan with over a decade shaping signature silhouettes for global fashion weeks and private clients.",
    specialties: "Precision Cuts, Structural Bobs, Editorial Styling",
    experience: "12+ Years",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
    instagram: "https://instagram.com",
    active: true,
    order: 1,
  },
  {
    id: "stf-2",
    name: "ELÉNA VANCE",
    slug: "elena-vance",
    role: "HEAD OF COLOUR & BALAYAGE",
    bio: "Specializing in low-maintenance French balayage, tonal harmonization, and bespoke platinum transformations.",
    specialties: "French Balayage, Micro-Highlights, Corrective Colour",
    experience: "9+ Years",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=80",
    instagram: "https://instagram.com",
    active: true,
    order: 2,
  },
  {
    id: "stf-3",
    name: "VIKRAM SINGHANIA",
    slug: "vikram-singhania",
    role: "MASTER STYLIST & SCALP SPECIALIST",
    bio: "Pioneer of holistic hair diagnostics, tailored texturizing shears, and reconstructive peptide therapy.",
    specialties: "Long Layers, Texture Rebalance, Japanese Head Spa",
    experience: "8+ Years",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=80",
    instagram: "https://instagram.com",
    active: true,
    order: 3,
  },
  {
    id: "stf-4",
    name: "MAYA DUBOIS",
    slug: "maya-dubois",
    role: "SENIOR EDITORIAL ARTIST",
    bio: "Celebrated for effortless red-carpet wave architecture and minimalist modern bridal aesthetics.",
    specialties: "Editorial Wave, Curtain Bangs, Gloss Treatments",
    experience: "7+ Years",
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80",
    instagram: "https://instagram.com",
    active: true,
    order: 4,
  },
];

export const INITIAL_PACKAGES = [
  {
    id: "pkg-1",
    name: "THE ESSENTIAL RITUAL",
    slug: "essential-ritual",
    price: 6500,
    duration: 90,
    description: "The foundational curation for ongoing refinement, clean lines, and balanced hydration.",
    includedServices: JSON.stringify([
      "Bespoke Consultation & Scalp Analysis",
      "Signature Precision Cut",
      "Detoxifying Botanical Hair Wash",
      "Sculpted Editorial Blow Dry & Style",
    ]),
    active: true,
    order: 1,
  },
  {
    id: "pkg-2",
    name: "THE SIGNATURE COUTURE",
    slug: "signature-couture",
    price: 14500,
    duration: 150,
    description: "Our most requested comprehensive ritual combining structural cut, dimensional gloss, and cellular rejuvenation.",
    includedServices: JSON.stringify([
      "Comprehensive Stylist Consultation",
      "Precision Cut & Texture Sculpting",
      "Tonal Gloss or Single-Process Colour",
      "Micro-Peptide Deep Keratin Infusion",
      "Thermal Defense & Signature Finish",
    ]),
    active: true,
    order: 2,
  },
  {
    id: "pkg-3",
    name: "THE COMPLETE TRANSFORMATION",
    slug: "complete-transformation",
    price: 24000,
    duration: 240,
    description: "An immersive, half-day master atelier journey delivering a radical, harmonious metamorphosis.",
    includedServices: JSON.stringify([
      "Private 1-on-1 Creative Director Consultation",
      "Full Hand-Painted French Balayage / Foilayage",
      "Acidic Bonding Gloss & Scalp Rebalancing",
      "Master Silhouette Re-Design Cut",
      "Cellular Steam & Aromatherapy Massage",
      "Editorial Styling & Home Care Formulation Kit",
    ]),
    active: true,
    order: 3,
  },
];

/* 100% Unique, Purpose-Specific Before/After Transformation Pairs */
export const INITIAL_BEFORE_AFTER = [
  {
    id: "ba-1",
    title: "Dimensional Sunlit Balayage & French Layering",
    category: "BALAYAGE",
    stylistId: "stf-2",
    serviceName: "French Balayage Melt",
    beforeImageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=1000&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&w=1000&q=80",
    description: "Shifted brassy warmth into cool creamy beige ribbons with face-framing illumination and seamless growth blending.",
    active: true,
    order: 1,
  },
  {
    id: "ba-2",
    title: "Architectural Precision Bob & Mirror Glaze",
    category: "CUT",
    stylistId: "stf-1",
    serviceName: "Precision Cut & Architecture",
    beforeImageUrl: "https://images.unsplash.com/photo-1584297091622-af8e5fd643bd?auto=format&fit=crop&w=1000&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=1000&q=80",
    description: "Removed heavy split ends to establish a razor-clean blunt jawline silhouette with inward bevel and mirror gloss.",
    active: true,
    order: 2,
  },
  {
    id: "ba-3",
    title: "Rich Espresso Brunette Depth & Velvet Shine",
    category: "COLOUR",
    stylistId: "stf-2",
    serviceName: "Haute Couture Colour",
    beforeImageUrl: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=1000&q=80",
    description: "Infused faded blonde strands with rich molten mocha undertones and high-luster acidic sealing.",
    active: true,
    order: 3,
  },
  {
    id: "ba-4",
    title: "Complete Metamorphosis: Soft Shag & Copper Glow",
    category: "TRANSFORMATION",
    stylistId: "stf-4",
    serviceName: "The Complete Transformation",
    beforeImageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1000&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=80",
    description: "Created effortless 70s-inspired feathered volume with custom terracotta-infused gloss tint.",
    active: true,
    order: 4,
  },
];

/* 100% Unique, Purpose-Specific Gallery Visuals */
export const INITIAL_GALLERY = [
  {
    id: "gal-1",
    title: "Monochrome Atelier Architecture",
    category: "INTERIOR",
    imageUrl: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "portrait",
    caption: "Minimalist travertine wash suites and warm shadowplay.",
    active: true,
    order: 1,
  },
  {
    id: "gal-2",
    title: "Scissors Angle & Shearing Mechanics",
    category: "CRAFT",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "landscape",
    caption: "Micro-point cutting for organic density dispersal.",
    active: true,
    order: 2,
  },
  {
    id: "gal-3",
    title: "Molten Clay & Terracotta Tonal Swatches",
    category: "DETAILS",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "portrait",
    caption: "Ammonia-free bespoke formulation bowls.",
    active: true,
    order: 3,
  },
  {
    id: "gal-4",
    title: "Fluid Movement & Cashmere Texture",
    category: "PORTRAIT",
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "square",
    caption: "Client post-treatment silhouette in natural daylight.",
    active: true,
    order: 4,
  },
  {
    id: "gal-5",
    title: "Travertine Styling Stations",
    category: "INTERIOR",
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "landscape",
    caption: "Private acoustic booths ensuring serene quiet luxury.",
    active: true,
    order: 5,
  },
  {
    id: "gal-6",
    title: "Master Colorist Formulation",
    category: "CRAFT",
    imageUrl: "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=1200&q=80",
    aspectRatio: "portrait",
    caption: "Custom calibrated pigments for undertone correction.",
    active: true,
    order: 6,
  },
];

/* 100% Unique, Authentic Client Portraits for Testimonials */
export const INITIAL_TESTIMONIALS = [
  {
    id: "tst-1",
    clientName: "ANANYA MEHTA",
    clientRole: "Architect & Spatial Designer",
    quote: "The attention to detail is completely different from anywhere I’ve been before. Aarav doesn’t just cut hair; he sculpts a silhouette that complements your facial bone structure effortlessly.",
    rating: 5,
    clientImageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    serviceName: "Precision Cut & Architecture",
    active: true,
    order: 1,
  },
  {
    id: "tst-2",
    clientName: "DEVANGI KAPOOR",
    clientRole: "Creative Producer",
    quote: "Eléna’s French balayage grew out seamlessly over six months with zero harsh lines. The space is a serene sanctuary—no loud music, no rushed energy, just quiet mastery.",
    rating: 5,
    clientImageUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80",
    serviceName: "French Balayage Melt",
    active: true,
    order: 2,
  },
  {
    id: "tst-3",
    clientName: "KABIR MALHOTRA",
    clientRole: "Managing Director",
    quote: "The scalp rejuvenation ritual is transformative. The tactile precision of the cut and the acoustic calm of the studio makes this an indispensable monthly ritual.",
    rating: 5,
    clientImageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    serviceName: "Masculine Grooming & Texture",
    active: true,
    order: 3,
  },
];

export const INITIAL_SETTINGS = {
  id: "singleton",
  salonName: "ATELIER ÉLAN",
  tagline: "Modern Hair Studio & Sanctuary",
  phone: "+91 98200 48192",
  whatsapp: "+919820048192",
  email: "concierge@atelier-elan.com",
  address: "14, Alipore Heritage Enclave, South Avenue, Mumbai 400001",
  openingHours: "Tuesday – Sunday: 10:00 AM – 08:30 PM | Monday: Private Studio Days",
  instagram: "@atelier.elan",
  googleMapsUrl: "https://maps.google.com/?q=Mumbai+Boutique+Salon",
};
